import reviewsJson from './reviews.json';

export interface Review {
  quote: string;
  name: string;
  rating: number;
}

export interface ReviewStats {
  reviews: Review[];
  totalReviews: number;
  averageRating: number;
}

export function fetchGoogleReviews(): ReviewStats {
  // Use static import of reviews.json generated by pre-build script
  return reviewsJson as ReviewStats;
}
