export interface Review {
  quote: string;
  name: string;
  rating: number;
}

export interface ReviewStats {
  reviews: Review[];
  totalReviews: number;
  averageRating: number;
}

export function getFallbackReviews(): ReviewStats {
  return {
    reviews: [
      {
        quote:
          "Gaby took photos at our friends' civil wedding ceremony. She was amazing from start to finish - very easy to contact, flexible with what we needed, super friendly and incredible photos! Turnaround with photos was also very quick - very impressive for such good quality work. Reasonably priced compared with competitors too. Thanks again Gaby!",
        name: "Charlotte Mills",
        rating: 5,
      },
      {
        quote:
          "We cannot recommend Gabi enough! She was the photographer for our wedding. Gabi captured every moment from entering the registry office to the end of our reception. She is a very talented and work driven young person with an eye for the details. Gabi, you were amazing, and we can't thank you enough for the beautiful photos!",
        name: "p 'peteto' pencheva",
        rating: 5,
      },
      {
        quote:
          "Thank you very much Miss Gaby ❤️ It was my son's first ever photo shoot and you did a great job!Photos are amazing and so natural, you have caught every little moments of my little one in a very creative and unique way And specifically thank you very much for being very calm and friendly with us and made the session run so smoothly and effectively. You are so talented and we are glad that we have met you ❤️ I highly recommend Mellsnap to everyone Thank you very much Miss Gaby ❤️ All the best 👍",
        name: "Hasitha Gunarathne",
        rating: 5,
      },
    ],
    totalReviews: 33,
    averageRating: 5.0,
  };
}

export async function fetchGoogleReviews(): Promise<ReviewStats> {
  try {
    // Import reviews.json generated by pre-build script
    const reviewsData = await import('./reviews.json');
    return reviewsData.default;
  } catch (error) {
    console.warn(
      'Could not load reviews.json (run prebuild script first). Using fallback reviews.',
      error
    );
    return getFallbackReviews();
  }
}
